# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'ImmiGuide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImmiGuide
  pod ‘lottie-ios’
  pod 'SnapKit', '~> 3.0'
end
